# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x0e\n\x0c\x45mptyRequest\"@\n\x04Rect\x12\x0c\n\x04left\x18\x01 \x02(\x02\x12\x0b\n\x03top\x18\x02 \x02(\x02\x12\r\n\x05right\x18\x03 \x02(\x02\x12\x0e\n\x06\x62ottom\x18\x04 \x02(\x02\"6\n\x07Pattern\x12\x14\n\x05image\x18\x01 \x02(\x0b\x32\x05.Rect\x12\x15\n\x06\x63olors\x18\x02 \x03(\x0b\x32\x05.Rect\"0\n\x12PatternsCollection\x12\x1a\n\x08patterns\x18\x01 \x03(\x0b\x32\x08.Pattern2?\n\x08Patterns\x12\x33\n\x0bGetPatterns\x12\r.EmptyRequest\x1a\x13.PatternsCollection\"\x00')



_EMPTYREQUEST = DESCRIPTOR.message_types_by_name['EmptyRequest']
_RECT = DESCRIPTOR.message_types_by_name['Rect']
_PATTERN = DESCRIPTOR.message_types_by_name['Pattern']
_PATTERNSCOLLECTION = DESCRIPTOR.message_types_by_name['PatternsCollection']
EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), {
  'DESCRIPTOR' : _RECT,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:Rect)
  })
_sym_db.RegisterMessage(Rect)

Pattern = _reflection.GeneratedProtocolMessageType('Pattern', (_message.Message,), {
  'DESCRIPTOR' : _PATTERN,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:Pattern)
  })
_sym_db.RegisterMessage(Pattern)

PatternsCollection = _reflection.GeneratedProtocolMessageType('PatternsCollection', (_message.Message,), {
  'DESCRIPTOR' : _PATTERNSCOLLECTION,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:PatternsCollection)
  })
_sym_db.RegisterMessage(PatternsCollection)

_PATTERNS = DESCRIPTOR.services_by_name['Patterns']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYREQUEST._serialized_start=16
  _EMPTYREQUEST._serialized_end=30
  _RECT._serialized_start=32
  _RECT._serialized_end=96
  _PATTERN._serialized_start=98
  _PATTERN._serialized_end=152
  _PATTERNSCOLLECTION._serialized_start=154
  _PATTERNSCOLLECTION._serialized_end=202
  _PATTERNS._serialized_start=204
  _PATTERNS._serialized_end=267
# @@protoc_insertion_point(module_scope)
